### PR TITLE
Update gather-support-information-6daa475.md

### PR DESCRIPTION
**Pull request by nikolasimeonov77**
This pull request is just a check that the bot works for the CLA.

### CODE REVIEW

**Comment by nikolasimeonov77** [comment]
Test

**Comment by nikolasimeonov77** [comment]
Test 2

**Comment by lyubomir-marinov** [comment]
Test 5

**Comment by lyubomir-marinov** [comment]
Test 6

**Comment by nikolasimeonov77** [comment]
> Thank you for your valuable content contribution, @nikolasimeonov77! So that we can [recognize your contribution in the SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please check your SAP Community user ID (this is a number) in your [personal settings page](https://community.sap.com/t5/user/myprofilepage/tab/personal-profile) and share it with us in a reply to this comment. Make sure you just include the number in the reply.
> 
> Your user ID is displayed as follows:
> 
> **Change display name for User ID N**
> 
> where N is your user ID. For example, [53 is the user ID of the user 'qmacro'](https://community.sap.com/t5/user/viewprofilepage/user-id/53).
> 
> Please note that we are currently refactoring our profile and badge system on the SAP Community, and will start assigning badges again when that's complete.

https://community.sap.com/t5/user/viewprofilepage/user-id/125418

**Comment by nikolasimeonov77** [comment]
https://community.sap.com/t5/user/viewprofilepage/user-id/125418

**Pull request merged**
